"""
reports.py - Report Generation: Formats terminal reports and exports to text files.
"""
from pathlib import Path
from student import Student
from analysis import PerformanceAnalyzer

class ReportGenerator:
    def __init__(self, export_dir: str = "reports"):
        self.export_dir = Path(export_dir)
        self.export_dir.mkdir(parents=True, exist_ok=True)

    def generate_detailed_report(self, student: Student) -> str:
        analysis = PerformanceAnalyzer.analyze_student(student)
        lines = [
            "=" * 60,
            "                 STUDENT ACADEMIC REPORT",
            "=" * 60,
            f"Student Name : {student.name}",
            f"Roll Number  : {student.roll_no}",
            f"Semester     : {student.semester}",
            f"Section      : {student.section}",
            "-" * 60,
            "SUBJECT PERFORMANCE",
            "-" * 60,
            f"{'Subject':<20}{'Marks':<12}{'Grade':<10}"
        ]

        if not student.marks:
            lines.append("No academic marks recorded.")
        else:
            for sub, (mark, grade) in analysis["breakdown"].items():
                mark_str = str(int(mark)) if mark.is_integer() else str(mark)
                lines.append(f"{sub:<20}{mark_str:<12}{grade:<10}")

            lines.extend([
                "-" * 60,
                f"Average Percentage : {analysis['average']}%",
                f"Overall Grade      : {analysis['overall_grade']}\n",
                f"Highest Marks      : {analysis['highest_sub']} ({int(analysis['highest_mark'])})",
                f"Lowest Marks       : {analysis['lowest_sub']} ({int(analysis['lowest_mark'])})\n",
                f"Attendance         : {int(student.attendance)}%\n",
                f"Performance Status : {analysis['status']}",
                "-" * 60,
                "Generated by Student Academic Performance Analyzer",
                "=" * 60
            ])

        return "\n".join(lines)

    def export_to_file(self, student: Student) -> str:
        content = self.generate_detailed_report(student)
        clean_name = student.name.split()[0]
        filepath = self.export_dir / f"{clean_name}_{student.roll_no}_report.txt"
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(content)
        return str(filepath)